version: "4"
services:
  mysql:
    image: mysql:8
    container_name: mysql_product_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: 'redis-cashing'
    image: 'redis:latest'
    ports:
      - '6379:6379'

  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_reservation: 300m
    ports:
      - "9411:9411"

  service-registry:
    image: guvalakat/service-registry_v2:latest
    container_name: service-registry
    ports:
      - "8761:8761"

  config-server:
    image: guvalakat/config-server_v2:latest
    container_name: config-server
    ports:
      - "9296:9296"
    environment:
#      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
    depends_on:
      - service-registry

  cloud-gateway:
    image: guvalakat/cloudgateway_v2:0.0.4
    container_name: cloud-gateway
    ports:
      - "9090:9090"
    environment:
#      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
#      - CONFIG_SERVER_URL=host.docker.internal
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
      - CONFIG_SERVER_URL=config-server
    depends_on:
      - config-server
    entrypoint: >
      /bin/sh -c '
        until curl -s http://config-server:9296/actuator/health; do
          echo "Waiting for config-server..."; sleep 5;
        done;
        exec java -jar /app/cloudgateway.jar'