server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
#    import: configserver:http://localhost:9296  # hard coding the config server URL
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
