apiVersion: v1
kind: Service
metadata:
    name: service-registry-svc
spec:
    selector:
        app: service-registry
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8761 # This is the port that the service is listening on inside the pod
    type: NodePort